#!/usr/bin/env bash
# print domains and subdomains

# Function to display information about a specific subdomain
display_subdomain_info() {
    local domain=$1
    local subdomain=$2

    # Retrieve DNS records for the specified subdomain
    records=$(dig +short $subdomain.$domain)

    # Determine the record type (A or CNAME) and the destination
    if [[ -n "$records" ]]; then
        record_type=$(echo "$records" | awk '{ if (tolower($1) == "cname") print "CNAME"; else print "A" }')
        destination=$(echo "$records" | awk '{ print $1 }')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "No records found for the subdomain $subdomain"
    fi
}

# Function to display information about default subdomains
display_default_subdomains_info() {
    local domain=$1

    # Display information for default subdomains www, lb-01, web-01, and web-02
    display_subdomain_info $domain www
    display_subdomain_info $domain lb-01
    display_subdomain_info $domain web-01
    display_subdomain_info $domain web-02
}

# Check if both domain and subdomain parameters are provided
if [[ $# -eq 2 ]]; then
    display_subdomain_info $1 $2
# Check if only the domain parameter is provided
elif [[ $# -eq 1 ]]; then
    display_default_subdomains_info $1
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
