#!/usr/bin/env bash

# Define the IP address and port
IP_ADDRESS="3.86.7.186"
PORT=8080

# Create a response string
RESPONSE="HTTP/1.1 200 OK\r\nContent-Length: 18\r\n\r\n<h1>Hello, world!</h1>"

# Continuously serve the response
while true; do
    echo -e "$RESPONSE" | nc -l -p $PORT -q 1
done
