#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update
apt-get install -y nginx

echo "Best School" | sudo tee /var/www/html/index.html

service nginx restartt
